version: '2'
services:
  todo_mongo:
    image: mongo
    container_name: todo_mongo
    hostname: todo_mongo
    ports:
      - 27017
    volumes:
      - /home/doris/todoactiviti/todo/data:/data/db
    command: mongod --directoryperdb 
    
  todo:
    depends_on:
      - todo_mongo
    image: dorissschoi/tododev
    container_name: todo
    hostname: todo
    ports:
      - 1337:1337
    volumes:
      - /home/doris/todoactiviti/development.coffee:/usr/src/app/config/env/development.coffee
      - /etc/ssl/certs:/etc/ssl/certs
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      
