version: '2'
services:
  todo_mongo:
    image: mongo
    container_name: todo_mongo
    hostname: todo_mongo
    ports:
      - 27107:27017
    volumes:
      - /home/jeffery/git/todoactiviti/mongoData:/data/db
    command: mongod --directoryperdb 
    
  todo:
    depends_on:
      - activiti_mysql
      - activiti_server
      - todo_mongo
    image: dorissschoi/todoactiviti
    container_name: todo
    hostname: todo
    ports:
      - 1337:1337
    volumes:
      - /home/jeffery/git/todoactiviti/config/env/development.coffee:/usr/src/app/config/env/development.coffee
      - /home/jeffery/git/todoactiviti/www/js/config/development.coffee:/usr/src/app/www/js/config/development.coffee
      - /home/jeffery/git/todoactiviti/entrypoint.sh:/usr/src/app/entrypoint.sh
        
  activiti_mysql:
    hostname: activiti_mysql
    container_name: activiti_mysql
    image: mariadb  
    ports:
      - 3306:3306
    volumes:
      - /home/jeffery/git/activiti/newmysqldata:/var/lib/mysql
      - /etc/localtime:/etc/localtime       
    environment:
      - MYSQL_ROOT_PASSWORD=pass1234
      - MYSQL_DATABASE=activiti_production
      - MYSQL_USER=activiti
      - MYSQL_PASSWORD=pass1234
  
  activiti_server:
    hostname: activiti_server
    container_name: activiti_server
    image: dorissschoi/activiti:latest
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/ssl/certs:/etc/ssl/certs       
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
    links:
      - activiti_mysql:mysql
    ports:
      - 8080:8080  
    environment:
      - DB_HOST=activiti_mysql
      - DB_PORT=3306
      - DB_NAME=activiti_production
      - DB_USER=activiti
      - DB_PASS=pass1234
      - http_proxy=http://proxy1.scig.gov.hk:8080
      - https_proxy=http://proxy1.scig.gov.hk:8080