version: '2'
services:
  todo_mongo:
    image: mongo
    container_name: todo_mongo
    hostname: todo_mongo
    ports:
      - 27017
    volumes:
      - /home/doris/todoactiviti/todo/data:/data/db
    command: mongod --directoryperdb 
    
  todo:
    depends_on:
      - todo_mongo
      - activiti-server
    image: dorissschoi/todoactiviti
    container_name: todo
    hostname: todo
    ports:
      - 1337:1337
    volumes:
      - ./config/docker/development.coffee:/usr/src/app/config/env/development.coffee
      - /etc/ssl/certs:/etc/ssl/certs
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      
  activiti-mysql:
    hostname: activiti-mysql
    container_name: activiti-mysql
    image: sameersbn/mysql:latest
    volumes:
      - /home/doris/activiti-mysql/data:/var/lib/mysql
    environment:
      - DB_NAME=activiti_production
      - DB_USER=activiti
      - DB_PASS=aaa123aa
  
  activiti-server:
    hostname: activiti-server
    container_name: activiti-server
    image: dorissschoi/activiti:latest
    links:
      - activiti-mysql:mysql
    ports:
      - 8080:8080  
    # for version 1 link env var
    environment:
      - DB_TYPE=mysql
      - DB_HOST=activiti-mysql
      - DB_PORT=3306
      # support for linked sameersbn/mysql image
      - DB_USER=activiti
      - DB_PASS=aaa123aa
      - DB_NAME=activiti_production